"""
将 biochem-chapters.json 转换为前端可视化的 JS 数据文件
运行: python export_for_frontend.py
输出: graph-data.js (被 preview-v3.html 引用)
"""

import json

with open("knowledge-base/verified/biochem-chapters.json") as f:
    nodes = json.load(f)

id_map = {n["id"]: n for n in nodes}

# 按 chapter 分组，构建章→节层级
chapters = {}
for n in nodes:
    if n["level"] == 1:
        chapters[n["chapter"]] = {
            "id": n["id"],
            "name": n["name"],
            "chapter": n["chapter"],
            "importance": n["importance"],
            "tags": n["tags"],
            "sections": []
        }

for n in nodes:
    if n["level"] == 2:
        ch = n["chapter"]
        if ch in chapters:
            section = {
                "id": n["id"],
                "name": n["name"],
                "section_code": n["section_code"],
                "importance": n["importance"],
                "tags": n["tags"],
                "prerequisites": n["prerequisites"],
                "related": n["related"],
                "subsections": []
            }
            # 找三级节点
            for n3 in nodes:
                if n3["level"] == 3 and n3["section_code"].startswith(n["section_code"] + "."):
                    section["subsections"].append({
                        "id": n3["id"],
                        "name": n3["name"],
                        "section_code": n3["section_code"],
                        "importance": n3["importance"],
                        "tags": n3["tags"],
                        "prerequisites": n3["prerequisites"],
                        "related": n3["related"],
                    })
            chapters[ch]["sections"].append(section)

# 构建 cross-reference 边（跨章依赖）
cross_refs = []
for n in nodes:
    for pid in n.get("prerequisites", []):
        if pid in id_map:
            parent_ch = id_map[pid]["chapter"]
            if parent_ch != n["chapter"]:
                cross_refs.append({
                    "source": pid,
                    "target": n["id"],
                    "type": "prerequisite"
                })
    for rid in n.get("related", []):
        if rid in id_map:
            related_ch = id_map[rid]["chapter"]
            if related_ch != n["chapter"]:
                cross_refs.append({
                    "source": n["id"],
                    "target": rid,
                    "type": "related"
                })

output = {
    "root": {"id": "biochem", "name": "生物化学"},
    "chapters": list(chapters.values()),
    "crossRefs": cross_refs,
    "stats": {
        "totalNodes": len(nodes),
        "chapters": len(chapters),
        "sections": len([n for n in nodes if n["level"] == 2]),
        "subsections": len([n for n in nodes if n["level"] == 3]),
        "crossRefs": len(cross_refs)
    }
}

js = f"// Auto-generated by export_for_frontend.py\nvar GRAPH_DATA = {json.dumps(output, ensure_ascii=False, indent=2)};\n"

with open("graph-data.js", "w", encoding="utf-8") as f:
    f.write(js)

print(f"✅ graph-data.js 已生成")
print(f"   {output['stats']}")
