// Auto-generated by export_for_frontend.py
var GRAPH_DATA = {
  "root": {
    "id": "biochem",
    "name": "生物化学"
  },
  "chapters": [
    {
      "id": "biochem-00",
      "name": "绪论",
      "chapter": 1,
      "importance": 3,
      "tags": [
        "绪论"
      ],
      "sections": [
        {
          "id": "biochem-00-01",
          "name": "生物化学的内容",
          "section_code": "1.1",
          "importance": 2,
          "tags": [
            "概述"
          ],
          "prerequisites": [],
          "related": [],
          "subsections": []
        },
        {
          "id": "biochem-00-02",
          "name": "生物化学的产生与发展",
          "section_code": "1.2",
          "importance": 2,
          "tags": [
            "科学史"
          ],
          "prerequisites": [],
          "related": [],
          "subsections": []
        },
        {
          "id": "biochem-00-03",
          "name": "生物化学的知识框架和学习方法",
          "section_code": "1.3",
          "importance": 3,
          "tags": [
            "方法论"
          ],
          "prerequisites": [],
          "related": [],
          "subsections": [
            {
              "id": "biochem-00-03-01",
              "name": "生命物质主要元素组成的规律",
              "section_code": "1.3.1",
              "importance": 2,
              "tags": [
                "元素组成"
              ],
              "prerequisites": [
                "biochem-00-03"
              ],
              "related": []
            },
            {
              "id": "biochem-00-03-02",
              "name": "生物大分子组成的共同规律",
              "section_code": "1.3.2",
              "importance": 3,
              "tags": [
                "生物大分子"
              ],
              "prerequisites": [
                "biochem-00-03"
              ],
              "related": []
            },
            {
              "id": "biochem-00-03-03",
              "name": "物质代谢和能量代谢的规律",
              "section_code": "1.3.3",
              "importance": 4,
              "tags": [
                "代谢",
                "能量"
              ],
              "prerequisites": [
                "biochem-00-03"
              ],
              "related": [
                "biochem-08"
              ]
            },
            {
              "id": "biochem-00-03-04",
              "name": "生物界遗传信息传递的规律",
              "section_code": "1.3.4",
              "importance": 4,
              "tags": [
                "中心法则",
                "遗传信息"
              ],
              "prerequisites": [
                "biochem-00-03"
              ],
              "related": [
                "biochem-13",
                "biochem-14",
                "biochem-15"
              ]
            }
          ]
        }
      ]
    },
    {
      "id": "biochem-02",
      "name": "蛋白质",
      "chapter": 2,
      "importance": 5,
      "tags": [
        "蛋白质",
        "氨基酸"
      ],
      "sections": [
        {
          "id": "biochem-02-01",
          "name": "蛋白质的分类",
          "section_code": "2.1",
          "importance": 2,
          "tags": [
            "分类"
          ],
          "prerequisites": [
            "biochem-02"
          ],
          "related": [],
          "subsections": []
        },
        {
          "id": "biochem-02-02",
          "name": "蛋白质的组成单位——氨基酸",
          "section_code": "2.2",
          "importance": 5,
          "tags": [
            "氨基酸"
          ],
          "prerequisites": [
            "biochem-02"
          ],
          "related": [
            "biochem-11-02"
          ],
          "subsections": [
            {
              "id": "biochem-02-02-01",
              "name": "氨基酸的结构通式",
              "section_code": "2.2.1",
              "importance": 4,
              "tags": [
                "氨基酸结构"
              ],
              "prerequisites": [
                "biochem-02-02"
              ],
              "related": []
            },
            {
              "id": "biochem-02-02-02",
              "name": "氨基酸的分类",
              "section_code": "2.2.2",
              "importance": 4,
              "tags": [
                "氨基酸分类"
              ],
              "prerequisites": [
                "biochem-02-02-01"
              ],
              "related": []
            },
            {
              "id": "biochem-02-02-03",
              "name": "氨基酸的理化性质",
              "section_code": "2.2.3",
              "importance": 4,
              "tags": [
                "等电点",
                "紫外吸收"
              ],
              "prerequisites": [
                "biochem-02-02-01"
              ],
              "related": []
            }
          ]
        },
        {
          "id": "biochem-02-03",
          "name": "肽",
          "section_code": "2.3",
          "importance": 3,
          "tags": [
            "肽键",
            "肽"
          ],
          "prerequisites": [
            "biochem-02-02"
          ],
          "related": [],
          "subsections": []
        },
        {
          "id": "biochem-02-04",
          "name": "蛋白质的结构",
          "section_code": "2.4",
          "importance": 5,
          "tags": [
            "一级结构",
            "空间结构"
          ],
          "prerequisites": [
            "biochem-02-03"
          ],
          "related": [],
          "subsections": [
            {
              "id": "biochem-02-04-01",
              "name": "蛋白质的一级结构",
              "section_code": "2.4.1",
              "importance": 5,
              "tags": [
                "一级结构",
                "序列"
              ],
              "prerequisites": [
                "biochem-02-04"
              ],
              "related": []
            },
            {
              "id": "biochem-02-04-02",
              "name": "蛋白质的空间结构",
              "section_code": "2.4.2",
              "importance": 5,
              "tags": [
                "二级结构",
                "三级结构",
                "四级结构"
              ],
              "prerequisites": [
                "biochem-02-04-01"
              ],
              "related": []
            }
          ]
        },
        {
          "id": "biochem-02-05",
          "name": "蛋白质结构与功能的关系",
          "section_code": "2.5",
          "importance": 4,
          "tags": [
            "结构功能"
          ],
          "prerequisites": [
            "biochem-02-04"
          ],
          "related": [],
          "subsections": []
        },
        {
          "id": "biochem-02-06",
          "name": "蛋白质的性质与分离、分析技术",
          "section_code": "2.6",
          "importance": 4,
          "tags": [
            "层析",
            "电泳",
            "分离纯化"
          ],
          "prerequisites": [
            "biochem-02-04"
          ],
          "related": [],
          "subsections": []
        }
      ]
    },
    {
      "id": "biochem-03",
      "name": "核酸",
      "chapter": 3,
      "importance": 5,
      "tags": [
        "DNA",
        "RNA",
        "核酸"
      ],
      "sections": [
        {
          "id": "biochem-03-01",
          "name": "核酸的组成成分",
          "section_code": "3.1",
          "importance": 4,
          "tags": [
            "戊糖",
            "碱基",
            "核苷酸"
          ],
          "prerequisites": [
            "biochem-03"
          ],
          "related": [],
          "subsections": []
        },
        {
          "id": "biochem-03-02",
          "name": "核酸的一级结构",
          "section_code": "3.2",
          "importance": 4,
          "tags": [
            "一级结构",
            "磷酸二酯键"
          ],
          "prerequisites": [
            "biochem-03-01"
          ],
          "related": [
            "biochem-02-04-01"
          ],
          "subsections": []
        },
        {
          "id": "biochem-03-03",
          "name": "DNA的二级结构",
          "section_code": "3.3",
          "importance": 5,
          "tags": [
            "双螺旋",
            "Watson-Crick"
          ],
          "prerequisites": [
            "biochem-03-02"
          ],
          "related": [],
          "subsections": []
        },
        {
          "id": "biochem-03-04",
          "name": "DNA的高级结构",
          "section_code": "3.4",
          "importance": 4,
          "tags": [
            "超螺旋",
            "染色体"
          ],
          "prerequisites": [
            "biochem-03-03"
          ],
          "related": [],
          "subsections": []
        },
        {
          "id": "biochem-03-05",
          "name": "DNA和基因组",
          "section_code": "3.5",
          "importance": 5,
          "tags": [
            "基因组",
            "基因"
          ],
          "prerequisites": [
            "biochem-03-04"
          ],
          "related": [
            "biochem-13"
          ],
          "subsections": []
        },
        {
          "id": "biochem-03-06",
          "name": "RNA的结构和功能",
          "section_code": "3.6",
          "importance": 5,
          "tags": [
            "tRNA",
            "rRNA",
            "mRNA",
            "非编码RNA"
          ],
          "prerequisites": [
            "biochem-03-02"
          ],
          "related": [
            "biochem-14"
          ],
          "subsections": []
        },
        {
          "id": "biochem-03-07",
          "name": "核酸的性质和研究方法",
          "section_code": "3.7",
          "importance": 4,
          "tags": [
            "变性",
            "复性",
            "杂交",
            "紫外吸收"
          ],
          "prerequisites": [
            "biochem-03"
          ],
          "related": [],
          "subsections": []
        },
        {
          "id": "biochem-03-08",
          "name": "核酸的序列测定",
          "section_code": "3.8",
          "importance": 4,
          "tags": [
            "测序",
            "Sanger",
            "高通量测序"
          ],
          "prerequisites": [
            "biochem-03-07"
          ],
          "related": [],
          "subsections": []
        }
      ]
    },
    {
      "id": "biochem-04",
      "name": "糖类",
      "chapter": 4,
      "importance": 4,
      "tags": [
        "糖",
        "碳水化合物"
      ],
      "sections": [
        {
          "id": "biochem-04-01",
          "name": "单糖",
          "section_code": "4.1",
          "importance": 4,
          "tags": [
            "单糖",
            "构型",
            "构象"
          ],
          "prerequisites": [
            "biochem-04"
          ],
          "related": [],
          "subsections": []
        },
        {
          "id": "biochem-04-02",
          "name": "重要单糖及其衍生物",
          "section_code": "4.2",
          "importance": 3,
          "tags": [
            "葡萄糖",
            "果糖"
          ],
          "prerequisites": [
            "biochem-04-01"
          ],
          "related": [],
          "subsections": []
        },
        {
          "id": "biochem-04-03",
          "name": "寡糖",
          "section_code": "4.3",
          "importance": 3,
          "tags": [
            "二糖",
            "寡糖"
          ],
          "prerequisites": [
            "biochem-04-01"
          ],
          "related": [],
          "subsections": []
        },
        {
          "id": "biochem-04-04",
          "name": "多糖",
          "section_code": "4.4",
          "importance": 4,
          "tags": [
            "淀粉",
            "糖原",
            "纤维素"
          ],
          "prerequisites": [
            "biochem-04-01"
          ],
          "related": [
            "biochem-09"
          ],
          "subsections": []
        },
        {
          "id": "biochem-04-05",
          "name": "糖复合物",
          "section_code": "4.5",
          "importance": 3,
          "tags": [
            "糖蛋白",
            "蛋白聚糖",
            "糖脂"
          ],
          "prerequisites": [
            "biochem-04",
            "biochem-02"
          ],
          "related": [],
          "subsections": []
        },
        {
          "id": "biochem-04-06",
          "name": "糖类研究方法",
          "section_code": "4.6",
          "importance": 2,
          "tags": [
            "糖类分析"
          ],
          "prerequisites": [
            "biochem-04"
          ],
          "related": [],
          "subsections": []
        }
      ]
    },
    {
      "id": "biochem-05",
      "name": "脂质和生物膜",
      "chapter": 5,
      "importance": 4,
      "tags": [
        "脂质",
        "生物膜"
      ],
      "sections": [
        {
          "id": "biochem-05-01",
          "name": "三酰甘油",
          "section_code": "5.1",
          "importance": 3,
          "tags": [
            "三酰甘油"
          ],
          "prerequisites": [
            "biochem-05"
          ],
          "related": [],
          "subsections": []
        },
        {
          "id": "biochem-05-02",
          "name": "脂肪酸",
          "section_code": "5.2",
          "importance": 4,
          "tags": [
            "脂肪酸",
            "必需脂肪酸"
          ],
          "prerequisites": [
            "biochem-05"
          ],
          "related": [
            "biochem-10"
          ],
          "subsections": []
        },
        {
          "id": "biochem-05-03",
          "name": "磷脂",
          "section_code": "5.3",
          "importance": 4,
          "tags": [
            "磷脂",
            "甘油磷脂"
          ],
          "prerequisites": [
            "biochem-05"
          ],
          "related": [],
          "subsections": []
        },
        {
          "id": "biochem-05-04",
          "name": "鞘脂",
          "section_code": "5.4",
          "importance": 3,
          "tags": [
            "鞘磷脂",
            "鞘糖脂"
          ],
          "prerequisites": [
            "biochem-05"
          ],
          "related": [],
          "subsections": []
        },
        {
          "id": "biochem-05-05",
          "name": "类固醇",
          "section_code": "5.5",
          "importance": 3,
          "tags": [
            "胆固醇",
            "类固醇"
          ],
          "prerequisites": [
            "biochem-05"
          ],
          "related": [],
          "subsections": []
        },
        {
          "id": "biochem-05-06",
          "name": "生物膜",
          "section_code": "5.6",
          "importance": 5,
          "tags": [
            "流动镶嵌模型",
            "膜蛋白",
            "膜转运"
          ],
          "prerequisites": [
            "biochem-05-03",
            "biochem-05-04"
          ],
          "related": [],
          "subsections": []
        }
      ]
    },
    {
      "id": "biochem-06",
      "name": "酶",
      "chapter": 6,
      "importance": 5,
      "tags": [
        "酶",
        "催化"
      ],
      "sections": [
        {
          "id": "biochem-06-01",
          "name": "酶的概念与特点",
          "section_code": "6.1",
          "importance": 4,
          "tags": [
            "酶定义",
            "高效性",
            "专一性"
          ],
          "prerequisites": [
            "biochem-06"
          ],
          "related": [],
          "subsections": []
        },
        {
          "id": "biochem-06-02",
          "name": "酶的化学本质与组成",
          "section_code": "6.2",
          "importance": 4,
          "tags": [
            "辅酶",
            "辅基",
            "单纯酶",
            "结合酶"
          ],
          "prerequisites": [
            "biochem-06-01",
            "biochem-02"
          ],
          "related": [],
          "subsections": []
        },
        {
          "id": "biochem-06-03",
          "name": "酶的命名与分类",
          "section_code": "6.3",
          "importance": 3,
          "tags": [
            "EC编号"
          ],
          "prerequisites": [
            "biochem-06-01"
          ],
          "related": [],
          "subsections": []
        },
        {
          "id": "biochem-06-04",
          "name": "酶的结构与功能",
          "section_code": "6.4",
          "importance": 5,
          "tags": [
            "活性部位",
            "必需基团",
            "同工酶"
          ],
          "prerequisites": [
            "biochem-06-02"
          ],
          "related": [],
          "subsections": []
        },
        {
          "id": "biochem-06-05",
          "name": "酶的专一性",
          "section_code": "6.5",
          "importance": 4,
          "tags": [
            "专一性",
            "锁钥模型",
            "诱导契合"
          ],
          "prerequisites": [
            "biochem-06-04"
          ],
          "related": [],
          "subsections": []
        },
        {
          "id": "biochem-06-06",
          "name": "酶的作用机制",
          "section_code": "6.6",
          "importance": 5,
          "tags": [
            "酶底物复合物",
            "催化机制"
          ],
          "prerequisites": [
            "biochem-06-04"
          ],
          "related": [],
          "subsections": []
        },
        {
          "id": "biochem-06-07",
          "name": "酶促反应动力学",
          "section_code": "6.7",
          "importance": 5,
          "tags": [
            "米氏方程",
            "Km",
            "Vmax"
          ],
          "prerequisites": [
            "biochem-06-06"
          ],
          "related": [],
          "subsections": []
        },
        {
          "id": "biochem-06-08",
          "name": "影响酶促反应速率的因素",
          "section_code": "6.8",
          "importance": 4,
          "tags": [
            "抑制剂",
            "竞争性抑制",
            "非竞争性抑制",
            "温度",
            "pH"
          ],
          "prerequisites": [
            "biochem-06-07"
          ],
          "related": [],
          "subsections": []
        },
        {
          "id": "biochem-06-09",
          "name": "酶活性的调节",
          "section_code": "6.9",
          "importance": 5,
          "tags": [
            "别构调控",
            "共价修饰",
            "酶原激活",
            "反馈调节"
          ],
          "prerequisites": [
            "biochem-06-08"
          ],
          "related": [
            "biochem-16"
          ],
          "subsections": []
        },
        {
          "id": "biochem-06-10",
          "name": "酶的研究方法与酶工程",
          "section_code": "6.10",
          "importance": 3,
          "tags": [
            "酶活力测定",
            "酶工程"
          ],
          "prerequisites": [
            "biochem-06"
          ],
          "related": [],
          "subsections": []
        }
      ]
    },
    {
      "id": "biochem-07",
      "name": "维生素和辅酶",
      "chapter": 7,
      "importance": 4,
      "tags": [
        "维生素",
        "辅酶"
      ],
      "sections": [
        {
          "id": "biochem-07-01",
          "name": "脂溶性维生素",
          "section_code": "7.1",
          "importance": 3,
          "tags": [
            "维生素A",
            "维生素D",
            "维生素E",
            "维生素K"
          ],
          "prerequisites": [
            "biochem-07",
            "biochem-05"
          ],
          "related": [],
          "subsections": []
        },
        {
          "id": "biochem-07-02",
          "name": "水溶性维生素",
          "section_code": "7.2",
          "importance": 5,
          "tags": [
            "B族维生素",
            "辅酶A",
            "NAD+",
            "FAD",
            "生物素",
            "叶酸"
          ],
          "prerequisites": [
            "biochem-07",
            "biochem-06"
          ],
          "related": [],
          "subsections": [
            {
              "id": "biochem-07-02-01",
              "name": "维生素B1和硫胺素焦磷酸",
              "section_code": "7.2.1",
              "importance": 3,
              "tags": [
                "维生素B1",
                "TPP",
                "脱羧"
              ],
              "prerequisites": [
                "biochem-07-02"
              ],
              "related": [
                "biochem-09-02"
              ]
            },
            {
              "id": "biochem-07-02-02",
              "name": "维生素B2和黄素辅酶",
              "section_code": "7.2.2",
              "importance": 3,
              "tags": [
                "维生素B2",
                "FAD",
                "FMN",
                "电子载体"
              ],
              "prerequisites": [
                "biochem-07-02"
              ],
              "related": [
                "biochem-08-02"
              ]
            },
            {
              "id": "biochem-07-02-03",
              "name": "泛酸和辅酶A",
              "section_code": "7.2.3",
              "importance": 4,
              "tags": [
                "泛酸",
                "辅酶A",
                "酰基载体"
              ],
              "prerequisites": [
                "biochem-07-02"
              ],
              "related": [
                "biochem-10-03",
                "biochem-09-02"
              ]
            },
            {
              "id": "biochem-07-02-04",
              "name": "维生素PP和烟酰胺辅酶",
              "section_code": "7.2.4",
              "importance": 4,
              "tags": [
                "维生素PP",
                "NAD+",
                "NADP+",
                "氧化还原"
              ],
              "prerequisites": [
                "biochem-07-02"
              ],
              "related": [
                "biochem-08-02"
              ]
            },
            {
              "id": "biochem-07-02-07",
              "name": "叶酸和叶酸辅酶",
              "section_code": "7.2.7",
              "importance": 4,
              "tags": [
                "叶酸",
                "一碳单位",
                "四氢叶酸"
              ],
              "prerequisites": [
                "biochem-07-02"
              ],
              "related": [
                "biochem-12-03",
                "biochem-11-03"
              ]
            },
            {
              "id": "biochem-07-02-10",
              "name": "维生素C",
              "section_code": "7.2.10",
              "importance": 3,
              "tags": [
                "维生素C",
                "抗坏血酸",
                "羟化反应"
              ],
              "prerequisites": [
                "biochem-07-02"
              ],
              "related": []
            }
          ]
        }
      ]
    },
    {
      "id": "biochem-08",
      "name": "新陈代谢总论与生物氧化",
      "chapter": 8,
      "importance": 5,
      "tags": [
        "代谢",
        "生物氧化",
        "呼吸链",
        "ATP"
      ],
      "sections": [
        {
          "id": "biochem-08-01",
          "name": "新陈代谢总论",
          "section_code": "8.1",
          "importance": 4,
          "tags": [
            "代谢途径",
            "高能化合物",
            "ATP",
            "磷酸肌酸"
          ],
          "prerequisites": [
            "biochem-08"
          ],
          "related": [
            "biochem-16"
          ],
          "subsections": []
        },
        {
          "id": "biochem-08-02",
          "name": "生物氧化",
          "section_code": "8.2",
          "importance": 5,
          "tags": [
            "呼吸链",
            "电子传递链",
            "氧化磷酸化",
            "化学渗透"
          ],
          "prerequisites": [
            "biochem-08-01"
          ],
          "related": [],
          "subsections": [
            {
              "id": "biochem-08-02-01",
              "name": "生物氧化的特点",
              "section_code": "8.2.1",
              "importance": 3,
              "tags": [
                "生物氧化",
                "特点"
              ],
              "prerequisites": [
                "biochem-08-02"
              ],
              "related": []
            },
            {
              "id": "biochem-08-02-02",
              "name": "呼吸链的组成及电子传递顺序",
              "section_code": "8.2.2",
              "importance": 5,
              "tags": [
                "复合体I-IV",
                "电子传递链",
                "辅酶Q",
                "细胞色素"
              ],
              "prerequisites": [
                "biochem-08-02",
                "biochem-07-02-02",
                "biochem-07-02-04"
              ],
              "related": []
            },
            {
              "id": "biochem-08-02-03",
              "name": "氧化磷酸化作用",
              "section_code": "8.2.3",
              "importance": 5,
              "tags": [
                "氧化磷酸化",
                "ATP合酶",
                "化学渗透假说",
                "P/O比"
              ],
              "prerequisites": [
                "biochem-08-02-02"
              ],
              "related": []
            },
            {
              "id": "biochem-08-02-04",
              "name": "胞质中NADH的跨膜转运",
              "section_code": "8.2.4",
              "importance": 4,
              "tags": [
                "穿梭系统",
                "苹果酸-天冬氨酸穿梭",
                "甘油-3-磷酸穿梭"
              ],
              "prerequisites": [
                "biochem-08-02-03"
              ],
              "related": []
            }
          ]
        }
      ]
    },
    {
      "id": "biochem-09",
      "name": "糖代谢",
      "chapter": 9,
      "importance": 5,
      "tags": [
        "糖代谢",
        "糖酵解",
        "TCA循环",
        "糖异生"
      ],
      "sections": [
        {
          "id": "biochem-09-01",
          "name": "多糖和低聚糖的酶促降解",
          "section_code": "9.1",
          "importance": 3,
          "tags": [
            "淀粉水解",
            "纤维素水解"
          ],
          "prerequisites": [
            "biochem-09",
            "biochem-06"
          ],
          "related": [],
          "subsections": []
        },
        {
          "id": "biochem-09-02",
          "name": "糖的分解代谢",
          "section_code": "9.2",
          "importance": 5,
          "tags": [
            "糖酵解",
            "有氧氧化",
            "三羧酸循环",
            "乙醛酸循环",
            "磷酸戊糖途径"
          ],
          "prerequisites": [
            "biochem-09",
            "biochem-08-02"
          ],
          "related": [],
          "subsections": [
            {
              "id": "biochem-09-02-01",
              "name": "糖酵解",
              "section_code": "9.2.1",
              "importance": 5,
              "tags": [
                "糖酵解",
                "EMP途径",
                "丙酮酸",
                "限速步骤"
              ],
              "prerequisites": [
                "biochem-09-02",
                "biochem-06-07"
              ],
              "related": []
            },
            {
              "id": "biochem-09-02-02",
              "name": "糖的有氧分解",
              "section_code": "9.2.2",
              "importance": 5,
              "tags": [
                "三羧酸循环",
                "TCA循环",
                "Krebs循环",
                "柠檬酸循环"
              ],
              "prerequisites": [
                "biochem-09-02-01",
                "biochem-08-02"
              ],
              "related": []
            },
            {
              "id": "biochem-09-02-03",
              "name": "乙醛酸循环",
              "section_code": "9.2.3",
              "importance": 3,
              "tags": [
                "乙醛酸循环",
                "乙醛酸体",
                "植物"
              ],
              "prerequisites": [
                "biochem-09-02-02"
              ],
              "related": []
            },
            {
              "id": "biochem-09-02-04",
              "name": "磷酸戊糖途径",
              "section_code": "9.2.4",
              "importance": 4,
              "tags": [
                "磷酸戊糖途径",
                "HMP途径",
                "NADPH",
                "核糖"
              ],
              "prerequisites": [
                "biochem-09-02"
              ],
              "related": []
            }
          ]
        },
        {
          "id": "biochem-09-03",
          "name": "糖的合成代谢",
          "section_code": "9.3",
          "importance": 4,
          "tags": [
            "糖原合成",
            "蔗糖合成",
            "淀粉合成",
            "糖异生"
          ],
          "prerequisites": [
            "biochem-09-02"
          ],
          "related": [],
          "subsections": [
            {
              "id": "biochem-09-03-04",
              "name": "糖异生作用",
              "section_code": "9.3.4",
              "importance": 5,
              "tags": [
                "糖异生",
                "丙酮酸羧化",
                "底物循环"
              ],
              "prerequisites": [
                "biochem-09-02-01",
                "biochem-09-03"
              ],
              "related": []
            }
          ]
        }
      ]
    },
    {
      "id": "biochem-10",
      "name": "脂质代谢",
      "chapter": 10,
      "importance": 5,
      "tags": [
        "脂质代谢",
        "β-氧化",
        "脂肪酸合成"
      ],
      "sections": [
        {
          "id": "biochem-10-01",
          "name": "脂质的酶促水解",
          "section_code": "10.1",
          "importance": 3,
          "tags": [
            "脂肪酶",
            "脂质水解"
          ],
          "prerequisites": [
            "biochem-10",
            "biochem-06"
          ],
          "related": [],
          "subsections": []
        },
        {
          "id": "biochem-10-02",
          "name": "三酰甘油的分解代谢",
          "section_code": "10.2",
          "importance": 5,
          "tags": [
            "β-氧化",
            "酮体",
            "甘油氧化"
          ],
          "prerequisites": [
            "biochem-10-01",
            "biochem-08-02"
          ],
          "related": [],
          "subsections": [
            {
              "id": "biochem-10-02-02",
              "name": "脂肪酸的β-氧化作用",
              "section_code": "10.2.2",
              "importance": 5,
              "tags": [
                "β-氧化",
                "脂肪酸降解",
                "乙酰辅酶A"
              ],
              "prerequisites": [
                "biochem-10-02",
                "biochem-08-02"
              ],
              "related": []
            },
            {
              "id": "biochem-10-02-04",
              "name": "酮体的生成和利用",
              "section_code": "10.2.4",
              "importance": 4,
              "tags": [
                "酮体",
                "乙酰乙酸",
                "β-羟基丁酸",
                "丙酮"
              ],
              "prerequisites": [
                "biochem-10-02-02"
              ],
              "related": []
            }
          ]
        },
        {
          "id": "biochem-10-03",
          "name": "三酰甘油的合成代谢",
          "section_code": "10.3",
          "importance": 4,
          "tags": [
            "脂肪酸合成",
            "三酰甘油合成"
          ],
          "prerequisites": [
            "biochem-10"
          ],
          "related": [],
          "subsections": [
            {
              "id": "biochem-10-03-02",
              "name": "脂肪酸的生物合成",
              "section_code": "10.3.2",
              "importance": 5,
              "tags": [
                "脂肪酸合成酶",
                "丙二酰辅酶A",
                "从头合成"
              ],
              "prerequisites": [
                "biochem-10-03",
                "biochem-09-02-02"
              ],
              "related": []
            }
          ]
        },
        {
          "id": "biochem-10-04",
          "name": "磷脂的代谢",
          "section_code": "10.4",
          "importance": 3,
          "tags": [
            "磷脂代谢"
          ],
          "prerequisites": [
            "biochem-10",
            "biochem-05-03"
          ],
          "related": [],
          "subsections": []
        },
        {
          "id": "biochem-10-05",
          "name": "胆固醇的代谢",
          "section_code": "10.5",
          "importance": 4,
          "tags": [
            "胆固醇合成",
            "胆固醇转化"
          ],
          "prerequisites": [
            "biochem-10",
            "biochem-05-05"
          ],
          "related": [],
          "subsections": []
        }
      ]
    },
    {
      "id": "biochem-11",
      "name": "蛋白质的降解和氨基酸代谢",
      "chapter": 11,
      "importance": 5,
      "tags": [
        "氨基酸代谢",
        "脱氨基",
        "尿素循环"
      ],
      "sections": [
        {
          "id": "biochem-11-01",
          "name": "蛋白质的酶促降解",
          "section_code": "11.1",
          "importance": 3,
          "tags": [
            "蛋白酶",
            "蛋白质降解"
          ],
          "prerequisites": [
            "biochem-11",
            "biochem-06"
          ],
          "related": [],
          "subsections": []
        },
        {
          "id": "biochem-11-02",
          "name": "氨基酸的分解代谢",
          "section_code": "11.2",
          "importance": 5,
          "tags": [
            "脱氨基",
            "脱羧基",
            "尿素循环",
            "氨代谢"
          ],
          "prerequisites": [
            "biochem-11-01",
            "biochem-02-02"
          ],
          "related": [],
          "subsections": [
            {
              "id": "biochem-11-02-01",
              "name": "氨基酸的脱氨基作用",
              "section_code": "11.2.1",
              "importance": 5,
              "tags": [
                "转氨基",
                "氧化脱氨基",
                "联合脱氨基"
              ],
              "prerequisites": [
                "biochem-11-02"
              ],
              "related": []
            },
            {
              "id": "biochem-11-02-03",
              "name": "氨的代谢去路",
              "section_code": "11.2.3",
              "importance": 5,
              "tags": [
                "尿素循环",
                "氨解毒",
                "谷氨酰胺"
              ],
              "prerequisites": [
                "biochem-11-02-01"
              ],
              "related": []
            }
          ]
        },
        {
          "id": "biochem-11-03",
          "name": "氨基酸合成代谢",
          "section_code": "11.3",
          "importance": 4,
          "tags": [
            "氨基酸合成",
            "一碳单位"
          ],
          "prerequisites": [
            "biochem-11-02"
          ],
          "related": [],
          "subsections": []
        }
      ]
    },
    {
      "id": "biochem-12",
      "name": "核苷酸代谢",
      "chapter": 12,
      "importance": 4,
      "tags": [
        "核苷酸代谢",
        "嘌呤",
        "嘧啶"
      ],
      "sections": [
        {
          "id": "biochem-12-01",
          "name": "核酸的酶促降解",
          "section_code": "12.1",
          "importance": 2,
          "tags": [
            "核酸酶"
          ],
          "prerequisites": [
            "biochem-12"
          ],
          "related": [],
          "subsections": []
        },
        {
          "id": "biochem-12-02",
          "name": "核苷酸的分解",
          "section_code": "12.2",
          "importance": 3,
          "tags": [
            "嘌呤分解",
            "嘧啶分解"
          ],
          "prerequisites": [
            "biochem-12-01"
          ],
          "related": [],
          "subsections": []
        },
        {
          "id": "biochem-12-03",
          "name": "核苷酸的生物合成",
          "section_code": "12.3",
          "importance": 5,
          "tags": [
            "从头合成",
            "补救合成",
            "嘌呤合成",
            "嘧啶合成"
          ],
          "prerequisites": [
            "biochem-12"
          ],
          "related": [],
          "subsections": []
        },
        {
          "id": "biochem-12-04",
          "name": "核苷酸生物合成的调节",
          "section_code": "12.4",
          "importance": 3,
          "tags": [
            "反馈调节"
          ],
          "prerequisites": [
            "biochem-12-03"
          ],
          "related": [
            "biochem-16"
          ],
          "subsections": []
        },
        {
          "id": "biochem-12-05",
          "name": "核苷酸合成的抗代谢物",
          "section_code": "12.5",
          "importance": 3,
          "tags": [
            "抗代谢物",
            "嘌呤类似物",
            "嘧啶类似物"
          ],
          "prerequisites": [
            "biochem-12-03"
          ],
          "related": [],
          "subsections": []
        },
        {
          "id": "biochem-12-06",
          "name": "辅酶核苷酸的生物合成",
          "section_code": "12.6",
          "importance": 3,
          "tags": [
            "NAD+",
            "FAD",
            "辅酶A合成"
          ],
          "prerequisites": [
            "biochem-12-03",
            "biochem-07"
          ],
          "related": [],
          "subsections": []
        }
      ]
    },
    {
      "id": "biochem-13",
      "name": "DNA的生物合成",
      "chapter": 13,
      "importance": 5,
      "tags": [
        "DNA复制",
        "中心法则"
      ],
      "sections": [
        {
          "id": "biochem-13-01",
          "name": "DNA复制的概况",
          "section_code": "13.1",
          "importance": 4,
          "tags": [
            "半保留复制",
            "复制起点"
          ],
          "prerequisites": [
            "biochem-13"
          ],
          "related": [],
          "subsections": []
        },
        {
          "id": "biochem-13-02",
          "name": "原核生物DNA的复制",
          "section_code": "13.2",
          "importance": 5,
          "tags": [
            "DNA聚合酶",
            "复制叉",
            "冈崎片段"
          ],
          "prerequisites": [
            "biochem-13-01"
          ],
          "related": [],
          "subsections": [
            {
              "id": "biochem-13-02-01",
              "name": "参与原核生物DNA复制的酶和蛋白质",
              "section_code": "13.2.1",
              "importance": 5,
              "tags": [
                "DNA聚合酶I/II/III",
                "解旋酶",
                "连接酶",
                "引物酶",
                "SSB"
              ],
              "prerequisites": [
                "biochem-13-02"
              ],
              "related": []
            },
            {
              "id": "biochem-13-02-03",
              "name": "DNA链的延伸",
              "section_code": "13.2.3",
              "importance": 5,
              "tags": [
                "前导链",
                "滞后链",
                "冈崎片段",
                "DNA连接酶"
              ],
              "prerequisites": [
                "biochem-13-02-01"
              ],
              "related": []
            }
          ]
        },
        {
          "id": "biochem-13-03",
          "name": "真核生物DNA的复制",
          "section_code": "13.3",
          "importance": 5,
          "tags": [
            "端粒",
            "复制许可"
          ],
          "prerequisites": [
            "biochem-13-02"
          ],
          "related": [],
          "subsections": []
        },
        {
          "id": "biochem-13-04",
          "name": "逆转录作用",
          "section_code": "13.4",
          "importance": 4,
          "tags": [
            "逆转录酶",
            "逆转录病毒"
          ],
          "prerequisites": [
            "biochem-13-01"
          ],
          "related": [],
          "subsections": []
        },
        {
          "id": "biochem-13-05",
          "name": "DNA的损伤与修复",
          "section_code": "13.5",
          "importance": 5,
          "tags": [
            "DNA损伤",
            "切除修复",
            "重组修复",
            "光修复"
          ],
          "prerequisites": [
            "biochem-13-01"
          ],
          "related": [],
          "subsections": [
            {
              "id": "biochem-13-05-02",
              "name": "DNA损伤的修复",
              "section_code": "13.5.2",
              "importance": 5,
              "tags": [
                "切除修复",
                "重组修复",
                "SOS修复",
                "光修复"
              ],
              "prerequisites": [
                "biochem-13-05"
              ],
              "related": []
            }
          ]
        },
        {
          "id": "biochem-13-06",
          "name": "DNA重组和克隆",
          "section_code": "13.6",
          "importance": 4,
          "tags": [
            "同源重组",
            "基因工程",
            "克隆"
          ],
          "prerequisites": [
            "biochem-13"
          ],
          "related": [],
          "subsections": []
        }
      ]
    },
    {
      "id": "biochem-14",
      "name": "RNA的生物合成",
      "chapter": 14,
      "importance": 5,
      "tags": [
        "转录",
        "RNA合成"
      ],
      "sections": [
        {
          "id": "biochem-14-01",
          "name": "RNA生物合成的概况",
          "section_code": "14.1",
          "importance": 3,
          "tags": [
            "转录概述"
          ],
          "prerequisites": [
            "biochem-14"
          ],
          "related": [],
          "subsections": []
        },
        {
          "id": "biochem-14-02",
          "name": "原核生物的转录",
          "section_code": "14.2",
          "importance": 5,
          "tags": [
            "RNA聚合酶",
            "启动子",
            "终止子"
          ],
          "prerequisites": [
            "biochem-14-01"
          ],
          "related": [],
          "subsections": [
            {
              "id": "biochem-14-02-01",
              "name": "原核生物的RNA聚合酶",
              "section_code": "14.2.1",
              "importance": 4,
              "tags": [
                "RNA聚合酶",
                "核心酶",
                "σ因子"
              ],
              "prerequisites": [
                "biochem-14-02"
              ],
              "related": []
            },
            {
              "id": "biochem-14-02-02",
              "name": "原核生物转录的起始",
              "section_code": "14.2.2",
              "importance": 4,
              "tags": [
                "启动子",
                "-10区",
                "-35区",
                "闭合复合物",
                "开放复合物"
              ],
              "prerequisites": [
                "biochem-14-02-01"
              ],
              "related": []
            }
          ]
        },
        {
          "id": "biochem-14-03",
          "name": "真核生物的转录",
          "section_code": "14.3",
          "importance": 5,
          "tags": [
            "RNA聚合酶I/II/III",
            "转录因子"
          ],
          "prerequisites": [
            "biochem-14-02"
          ],
          "related": [],
          "subsections": []
        },
        {
          "id": "biochem-14-04",
          "name": "原核生物和真核生物转录调控的特点",
          "section_code": "14.4",
          "importance": 4,
          "tags": [
            "转录调控",
            "操纵子",
            "增强子"
          ],
          "prerequisites": [
            "biochem-14-02",
            "biochem-14-03"
          ],
          "related": [
            "biochem-16"
          ],
          "subsections": []
        },
        {
          "id": "biochem-14-05",
          "name": "转录的选择性抑制",
          "section_code": "14.5",
          "importance": 3,
          "tags": [
            "利福霉素",
            "α-鹅膏蕈碱"
          ],
          "prerequisites": [
            "biochem-14-02"
          ],
          "related": [],
          "subsections": []
        },
        {
          "id": "biochem-14-06",
          "name": "转录产物的加工",
          "section_code": "14.6",
          "importance": 5,
          "tags": [
            "内含子剪接",
            "5'加帽",
            "3'加尾",
            "RNA编辑"
          ],
          "prerequisites": [
            "biochem-14-03"
          ],
          "related": [],
          "subsections": [
            {
              "id": "biochem-14-06-01",
              "name": "内含子剪接的四种类型",
              "section_code": "14.6.1",
              "importance": 4,
              "tags": [
                "内含子",
                "外显子",
                "剪接体",
                "自剪接"
              ],
              "prerequisites": [
                "biochem-14-06"
              ],
              "related": []
            }
          ]
        },
        {
          "id": "biochem-14-07",
          "name": "RNA的复制",
          "section_code": "14.7",
          "importance": 3,
          "tags": [
            "RNA病毒",
            "RNA复制酶"
          ],
          "prerequisites": [
            "biochem-14-01"
          ],
          "related": [],
          "subsections": []
        }
      ]
    },
    {
      "id": "biochem-15",
      "name": "蛋白质的生物合成",
      "chapter": 15,
      "importance": 5,
      "tags": [
        "翻译",
        "蛋白质合成"
      ],
      "sections": [
        {
          "id": "biochem-15-01",
          "name": "蛋白质合成体系",
          "section_code": "15.1",
          "importance": 5,
          "tags": [
            "mRNA",
            "核糖体",
            "tRNA",
            "密码子"
          ],
          "prerequisites": [
            "biochem-15"
          ],
          "related": [],
          "subsections": []
        },
        {
          "id": "biochem-15-02",
          "name": "蛋白质的合成过程",
          "section_code": "15.2",
          "importance": 5,
          "tags": [
            "起始",
            "延长",
            "终止",
            "氨酰-tRNA"
          ],
          "prerequisites": [
            "biochem-15-01"
          ],
          "related": [],
          "subsections": [
            {
              "id": "biochem-15-02-03",
              "name": "肽链合成的起始",
              "section_code": "15.2.3",
              "importance": 4,
              "tags": [
                "起始密码子",
                "起始因子",
                "核糖体组装"
              ],
              "prerequisites": [
                "biochem-15-02"
              ],
              "related": []
            },
            {
              "id": "biochem-15-02-04",
              "name": "肽链合成的延长",
              "section_code": "15.2.4",
              "importance": 4,
              "tags": [
                "进位",
                "转肽",
                "移位",
                "延长因子"
              ],
              "prerequisites": [
                "biochem-15-02-03"
              ],
              "related": []
            },
            {
              "id": "biochem-15-02-05",
              "name": "肽链合成的终止",
              "section_code": "15.2.5",
              "importance": 3,
              "tags": [
                "终止密码子",
                "释放因子"
              ],
              "prerequisites": [
                "biochem-15-02-04"
              ],
              "related": []
            }
          ]
        },
        {
          "id": "biochem-15-03",
          "name": "蛋白质合成后的加工",
          "section_code": "15.3",
          "importance": 4,
          "tags": [
            "翻译后修饰",
            "折叠",
            "剪切"
          ],
          "prerequisites": [
            "biochem-15-02"
          ],
          "related": [],
          "subsections": []
        },
        {
          "id": "biochem-15-04",
          "name": "蛋白质合成所需的能量",
          "section_code": "15.4",
          "importance": 3,
          "tags": [
            "GTP",
            "ATP",
            "能量消耗"
          ],
          "prerequisites": [
            "biochem-15-02",
            "biochem-08-01"
          ],
          "related": [],
          "subsections": []
        },
        {
          "id": "biochem-15-05",
          "name": "蛋白质的定向转运",
          "section_code": "15.5",
          "importance": 4,
          "tags": [
            "信号肽",
            "分泌蛋白",
            "膜蛋白插入"
          ],
          "prerequisites": [
            "biochem-15-03",
            "biochem-05-06"
          ],
          "related": [],
          "subsections": []
        },
        {
          "id": "biochem-15-06",
          "name": "蛋白质合成的抑制剂",
          "section_code": "15.6",
          "importance": 3,
          "tags": [
            "抗生素",
            "毒素"
          ],
          "prerequisites": [
            "biochem-15-02"
          ],
          "related": [],
          "subsections": []
        },
        {
          "id": "biochem-15-07",
          "name": "寡肽的生物合成",
          "section_code": "15.7",
          "importance": 2,
          "tags": [
            "非核糖体肽"
          ],
          "prerequisites": [
            "biochem-15-02"
          ],
          "related": [],
          "subsections": []
        }
      ]
    },
    {
      "id": "biochem-16",
      "name": "物质代谢的调节控制",
      "chapter": 16,
      "importance": 5,
      "tags": [
        "代谢调控",
        "激素",
        "基因表达调控"
      ],
      "sections": [
        {
          "id": "biochem-16-01",
          "name": "物质代谢的相互联系",
          "section_code": "16.1",
          "importance": 5,
          "tags": [
            "代谢网络",
            "代谢互锁"
          ],
          "prerequisites": [
            "biochem-16"
          ],
          "related": [
            "biochem-09",
            "biochem-10",
            "biochem-11",
            "biochem-12"
          ],
          "subsections": []
        },
        {
          "id": "biochem-16-02",
          "name": "分子水平的调节",
          "section_code": "16.2",
          "importance": 5,
          "tags": [
            "酶活性调节",
            "别构调节",
            "共价修饰",
            "基因表达调控"
          ],
          "prerequisites": [
            "biochem-16",
            "biochem-06-09"
          ],
          "related": [],
          "subsections": [
            {
              "id": "biochem-16-02-02",
              "name": "基因表达的调节",
              "section_code": "16.2.2",
              "importance": 5,
              "tags": [
                "lac操纵子",
                "trp操纵子",
                "转录调控",
                "转录后调控"
              ],
              "prerequisites": [
                "biochem-16-02",
                "biochem-14-04"
              ],
              "related": []
            }
          ]
        },
        {
          "id": "biochem-16-03",
          "name": "细胞水平的调节",
          "section_code": "16.3",
          "importance": 4,
          "tags": [
            "细胞区室化",
            "膜转运调控"
          ],
          "prerequisites": [
            "biochem-16-02",
            "biochem-05-06"
          ],
          "related": [],
          "subsections": []
        },
        {
          "id": "biochem-16-04",
          "name": "多细胞整体水平的调节",
          "section_code": "16.4",
          "importance": 4,
          "tags": [
            "激素调节",
            "神经调节",
            "整体代谢"
          ],
          "prerequisites": [
            "biochem-16-02",
            "biochem-16-03"
          ],
          "related": [],
          "subsections": [
            {
              "id": "biochem-16-04-01",
              "name": "激素对代谢的调节",
              "section_code": "16.4.1",
              "importance": 4,
              "tags": [
                "胰岛素",
                "胰高血糖素",
                "肾上腺素",
                "第二信使"
              ],
              "prerequisites": [
                "biochem-16-04"
              ],
              "related": []
            }
          ]
        }
      ]
    }
  ],
  "crossRefs": [
    {
      "source": "biochem-00-03-03",
      "target": "biochem-08",
      "type": "related"
    },
    {
      "source": "biochem-00-03-04",
      "target": "biochem-13",
      "type": "related"
    },
    {
      "source": "biochem-00-03-04",
      "target": "biochem-14",
      "type": "related"
    },
    {
      "source": "biochem-00-03-04",
      "target": "biochem-15",
      "type": "related"
    },
    {
      "source": "biochem-00",
      "target": "biochem-02",
      "type": "prerequisite"
    },
    {
      "source": "biochem-02",
      "target": "biochem-03",
      "type": "related"
    },
    {
      "source": "biochem-02",
      "target": "biochem-11",
      "type": "related"
    },
    {
      "source": "biochem-02-02",
      "target": "biochem-11-02",
      "type": "related"
    },
    {
      "source": "biochem-00",
      "target": "biochem-03",
      "type": "prerequisite"
    },
    {
      "source": "biochem-03",
      "target": "biochem-02",
      "type": "related"
    },
    {
      "source": "biochem-03",
      "target": "biochem-12",
      "type": "related"
    },
    {
      "source": "biochem-03",
      "target": "biochem-13",
      "type": "related"
    },
    {
      "source": "biochem-03-02",
      "target": "biochem-02-04-01",
      "type": "related"
    },
    {
      "source": "biochem-03-05",
      "target": "biochem-13",
      "type": "related"
    },
    {
      "source": "biochem-03-06",
      "target": "biochem-14",
      "type": "related"
    },
    {
      "source": "biochem-00",
      "target": "biochem-04",
      "type": "prerequisite"
    },
    {
      "source": "biochem-04",
      "target": "biochem-09",
      "type": "related"
    },
    {
      "source": "biochem-04-04",
      "target": "biochem-09",
      "type": "related"
    },
    {
      "source": "biochem-02",
      "target": "biochem-04-05",
      "type": "prerequisite"
    },
    {
      "source": "biochem-00",
      "target": "biochem-05",
      "type": "prerequisite"
    },
    {
      "source": "biochem-05",
      "target": "biochem-10",
      "type": "related"
    },
    {
      "source": "biochem-05-02",
      "target": "biochem-10",
      "type": "related"
    },
    {
      "source": "biochem-02",
      "target": "biochem-06",
      "type": "prerequisite"
    },
    {
      "source": "biochem-06",
      "target": "biochem-08",
      "type": "related"
    },
    {
      "source": "biochem-06",
      "target": "biochem-09",
      "type": "related"
    },
    {
      "source": "biochem-06",
      "target": "biochem-10",
      "type": "related"
    },
    {
      "source": "biochem-02",
      "target": "biochem-06-02",
      "type": "prerequisite"
    },
    {
      "source": "biochem-06-09",
      "target": "biochem-16",
      "type": "related"
    },
    {
      "source": "biochem-06",
      "target": "biochem-07",
      "type": "prerequisite"
    },
    {
      "source": "biochem-05",
      "target": "biochem-07-01",
      "type": "prerequisite"
    },
    {
      "source": "biochem-06",
      "target": "biochem-07-02",
      "type": "prerequisite"
    },
    {
      "source": "biochem-06",
      "target": "biochem-08",
      "type": "prerequisite"
    },
    {
      "source": "biochem-08",
      "target": "biochem-09",
      "type": "related"
    },
    {
      "source": "biochem-08",
      "target": "biochem-10",
      "type": "related"
    },
    {
      "source": "biochem-08",
      "target": "biochem-11",
      "type": "related"
    },
    {
      "source": "biochem-08-01",
      "target": "biochem-16",
      "type": "related"
    },
    {
      "source": "biochem-04",
      "target": "biochem-09",
      "type": "prerequisite"
    },
    {
      "source": "biochem-08",
      "target": "biochem-09",
      "type": "prerequisite"
    },
    {
      "source": "biochem-09",
      "target": "biochem-10",
      "type": "related"
    },
    {
      "source": "biochem-09",
      "target": "biochem-16",
      "type": "related"
    },
    {
      "source": "biochem-06",
      "target": "biochem-09-01",
      "type": "prerequisite"
    },
    {
      "source": "biochem-08-02",
      "target": "biochem-09-02",
      "type": "prerequisite"
    },
    {
      "source": "biochem-05",
      "target": "biochem-10",
      "type": "prerequisite"
    },
    {
      "source": "biochem-08",
      "target": "biochem-10",
      "type": "prerequisite"
    },
    {
      "source": "biochem-10",
      "target": "biochem-09",
      "type": "related"
    },
    {
      "source": "biochem-06",
      "target": "biochem-10-01",
      "type": "prerequisite"
    },
    {
      "source": "biochem-08-02",
      "target": "biochem-10-02",
      "type": "prerequisite"
    },
    {
      "source": "biochem-05-03",
      "target": "biochem-10-04",
      "type": "prerequisite"
    },
    {
      "source": "biochem-05-05",
      "target": "biochem-10-05",
      "type": "prerequisite"
    },
    {
      "source": "biochem-02",
      "target": "biochem-11",
      "type": "prerequisite"
    },
    {
      "source": "biochem-08",
      "target": "biochem-11",
      "type": "prerequisite"
    },
    {
      "source": "biochem-11",
      "target": "biochem-09",
      "type": "related"
    },
    {
      "source": "biochem-11",
      "target": "biochem-10",
      "type": "related"
    },
    {
      "source": "biochem-06",
      "target": "biochem-11-01",
      "type": "prerequisite"
    },
    {
      "source": "biochem-02-02",
      "target": "biochem-11-02",
      "type": "prerequisite"
    },
    {
      "source": "biochem-03",
      "target": "biochem-12",
      "type": "prerequisite"
    },
    {
      "source": "biochem-08",
      "target": "biochem-12",
      "type": "prerequisite"
    },
    {
      "source": "biochem-12",
      "target": "biochem-13",
      "type": "related"
    },
    {
      "source": "biochem-12",
      "target": "biochem-14",
      "type": "related"
    },
    {
      "source": "biochem-12-04",
      "target": "biochem-16",
      "type": "related"
    },
    {
      "source": "biochem-07",
      "target": "biochem-12-06",
      "type": "prerequisite"
    },
    {
      "source": "biochem-03",
      "target": "biochem-13",
      "type": "prerequisite"
    },
    {
      "source": "biochem-08",
      "target": "biochem-13",
      "type": "prerequisite"
    },
    {
      "source": "biochem-13",
      "target": "biochem-14",
      "type": "related"
    },
    {
      "source": "biochem-13",
      "target": "biochem-15",
      "type": "related"
    },
    {
      "source": "biochem-03",
      "target": "biochem-14",
      "type": "prerequisite"
    },
    {
      "source": "biochem-13",
      "target": "biochem-14",
      "type": "prerequisite"
    },
    {
      "source": "biochem-14",
      "target": "biochem-15",
      "type": "related"
    },
    {
      "source": "biochem-14-04",
      "target": "biochem-16",
      "type": "related"
    },
    {
      "source": "biochem-02",
      "target": "biochem-15",
      "type": "prerequisite"
    },
    {
      "source": "biochem-14",
      "target": "biochem-15",
      "type": "prerequisite"
    },
    {
      "source": "biochem-15",
      "target": "biochem-13",
      "type": "related"
    },
    {
      "source": "biochem-08-01",
      "target": "biochem-15-04",
      "type": "prerequisite"
    },
    {
      "source": "biochem-05-06",
      "target": "biochem-15-05",
      "type": "prerequisite"
    },
    {
      "source": "biochem-09",
      "target": "biochem-16",
      "type": "prerequisite"
    },
    {
      "source": "biochem-10",
      "target": "biochem-16",
      "type": "prerequisite"
    },
    {
      "source": "biochem-11",
      "target": "biochem-16",
      "type": "prerequisite"
    },
    {
      "source": "biochem-16-01",
      "target": "biochem-09",
      "type": "related"
    },
    {
      "source": "biochem-16-01",
      "target": "biochem-10",
      "type": "related"
    },
    {
      "source": "biochem-16-01",
      "target": "biochem-11",
      "type": "related"
    },
    {
      "source": "biochem-16-01",
      "target": "biochem-12",
      "type": "related"
    },
    {
      "source": "biochem-06-09",
      "target": "biochem-16-02",
      "type": "prerequisite"
    },
    {
      "source": "biochem-05-06",
      "target": "biochem-16-03",
      "type": "prerequisite"
    },
    {
      "source": "biochem-07-02-01",
      "target": "biochem-09-02",
      "type": "related"
    },
    {
      "source": "biochem-07-02-02",
      "target": "biochem-08-02",
      "type": "related"
    },
    {
      "source": "biochem-07-02-03",
      "target": "biochem-10-03",
      "type": "related"
    },
    {
      "source": "biochem-07-02-03",
      "target": "biochem-09-02",
      "type": "related"
    },
    {
      "source": "biochem-07-02-04",
      "target": "biochem-08-02",
      "type": "related"
    },
    {
      "source": "biochem-07-02-07",
      "target": "biochem-12-03",
      "type": "related"
    },
    {
      "source": "biochem-07-02-07",
      "target": "biochem-11-03",
      "type": "related"
    },
    {
      "source": "biochem-07-02-02",
      "target": "biochem-08-02-02",
      "type": "prerequisite"
    },
    {
      "source": "biochem-07-02-04",
      "target": "biochem-08-02-02",
      "type": "prerequisite"
    },
    {
      "source": "biochem-06-07",
      "target": "biochem-09-02-01",
      "type": "prerequisite"
    },
    {
      "source": "biochem-08-02",
      "target": "biochem-09-02-02",
      "type": "prerequisite"
    },
    {
      "source": "biochem-08-02",
      "target": "biochem-10-02-02",
      "type": "prerequisite"
    },
    {
      "source": "biochem-09-02-02",
      "target": "biochem-10-03-02",
      "type": "prerequisite"
    },
    {
      "source": "biochem-14-04",
      "target": "biochem-16-02-02",
      "type": "prerequisite"
    }
  ],
  "stats": {
    "totalNodes": 140,
    "chapters": 16,
    "sections": 84,
    "subsections": 40,
    "crossRefs": 97
  }
};
